---
abstract: 'Routines for text containing ANSI escape codes'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Data::Dump: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ANSI-Util
requires:
  Text::WideChar::Util: 0.07
  perl: 5.010001
resources: {}
version: 0.12
