---
abstract: 'Routines for text containing ANSI escape codes'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Data::Dump: 0
  Module::Build: 0.3601
  Test::More: 0.98
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ANSI-Util
requires:
  Text::CharWidth: 0
  Text::WideChar::Util: 0.04
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Text-ANSI-Util
  repository: http://github.com/sharyanto/perl-Text-ANSI-Util
version: 0.10
